movie_library/routes.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    session,
    redirect,
    request,
    current_app,
    flash,
)
import functools
from movie_library.forms import MovieForm, Extension, RegisterForm, LoginForm
from dataclasses import asdict
from movie_library.database import MovieDB
import uuid
from movie_library.movies import Movie, User
from passlib.hash import pbkdf2_sha256
import os

# Creating a Flask Blueprint for organized route and view management
pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


# Decorator function to ensure authentication for routes requiring logged-in users
def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))
        return route(*args, **kwargs)

    return route_wrapper


# Home page route displaying the user's watchlist for authenticated users
@pages.route("/")
@login_required
def index():
    # Retrieving user and movie data from the database
    user_data = current_app.db.user.find_one({"email": session["email"]})
    user = User(**user_data)

    movie_data = current_app.db.movies.find({"_id": {"$in": user.movies}})
    mymovies = [Movie(**movie) for movie in movie_data]
    return render_template(
        "index.jinja", title="Movies Watchlist", movies_data=mymovies
    )


# User registration route allowing users to register with a unique email and securely hashed password
@pages.route("/register", methods=["GET", "POST"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))
    form = RegisterForm()

    if form.validate_on_submit():
        # Creating a new user and inserting into the database
        user = User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data),
        )

        current_app.db.user.insert_one(asdict(user))
        flash("User registered succesfully", "Success")

        return redirect(url_for(".login"))

    return render_template(
        "register.jinja", title="Movies Watchlist - Register", form=form
    )


# User login route enabling users to log in securely
@pages.route("/login", methods=["GET", "POST"])
def login():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_data = current_app.db.user.find_one({"email": form.email.data})
        if not user_data:
            flash("Login credentials are not correct", category="danger")
            return redirect(url_for(".login"))
        user = User(**user_data)

        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            # Setting user session upon successful login
            session["user_id"] = user._id
            session["email"] = user.email

            return redirect(url_for(".index"))

        flash("Login credentials are not correct", category="danger")

    return render_template("login.jinja", title="Movie Watchlist - Login", form=form)


# User logout route logging out the currently authenticated user
@pages.route("/logout")
def logout():
    session.clear()
    return redirect(url_for(".login"))


# Add movie route allowing authenticated users to add new movies to their watchlist
@pages.route("/add", methods=["GET", "POST"])
@login_required
def add_movie():
    form = MovieForm()

    if form.validate_on_submit():
        # Creating a new movie and updating the user's watchlist in the database
        movie = Movie(
            _id=uuid.uuid4().hex,
            title=form.title.data,
            director=form.director.data,
            year=form.year.data,
        )
        current_app.db.movies.insert_one(asdict(movie))
        current_app.db.user.update_one(
            {"_id": session["user_id"]}, {"$push": {"movies": movie._id}}
        )

        return redirect(url_for(".index"))

    return render_template(
        "new_movie.jinja", title="Movies Watchlist - Add Movie", form=form
    )


# Edit movie route allowing users to edit details of a specific movie
@pages.route("/edit/movie/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_movie(_id: str):
    movie_data = current_app.db.movies.find_one({"_id": _id})
    movie = Movie(**movie_data)
    form = Extension(obj=movie)

    if form.validate_on_submit():
        # Updating movie details in the database upon form validation
        print(f"Form validated. Values: {form.data}")

        movie.title = form.title.data
        movie.director = form.director.data
        movie.year = form.year.data
        movie.tag1 = form.tag1.data
        movie.tag2 = form.tag2.data
        movie.video_link = form.video_link.data

        current_app.db.movies.update_one({"_id": movie._id}, {"$set": asdict(movie)})
        return redirect(url_for(".movie", _id=_id))
    return render_template("movie_form.jinja", movie=movie, form=form)


# Delete movie route enabling users to delete a specific movie
@pages.route("/delete/movie/<string:_id>", methods=["GET", "POST"])
@login_required
def delete_movie(_id: str):
    current_app.db.user.update_one(
        {"_id": session["user_id"]}, {"$pull": {"movies": _id}}
    )
    return redirect(url_for(".index"))


# View movie details route displaying detailed information about a specific movie
@pages.get("/movie/<string:_id>")
def movie(_id: str):
    movie_data = current_app.db.movies.find_one({"_id": _id})
    movie = Movie(**movie_data)

    return render_template("movie_details.jinja", movie=movie)


# Rate movie route allowing users to rate a specific movie
@pages.get("/movie/<string:_id>/rate")
@login_required
def rate_movie(_id):
    rating = int(request.args.get("rating"))
    current_app.db.movies.update_one({"_id": _id}, {"$set": {"rating": rating}})
    return redirect(url_for(".movie", _id=_id))


# Mark movie as watched route allowing users to mark a movie as watched or not watched
@pages.get("/movie/<string:_id>/watch")
@login_required
def watch_today(_id):
    movie_data = current_app.db.movies.find_one({"_id": _id})

    if movie_data:
        current_state = movie_data.get("last_watched", None)
        new_state = "Not Watched" if current_state == "Watched" else "Watched"

        current_app.db.movies.update_one(
            {"_id": _id}, {"$set": {"last_watched": new_state}}
        )

        flash(f"Movie marked as {new_state}", "Success")

    return redirect(url_for(".movie", _id=_id))


# Search movies route providing a search interface for users to find movies in the database
@pages.route("/search", methods=["GET", "POST"])
@login_required
def search_movies():
    if request.method == "GET":
        return render_template(
            "search.jinja", title="Movies Watchlist - Database Search"
        )

    if request.method == "POST":
        search_query = request.form.get("search_query", "")

        # Use the MovieDB class to search for movies
        API_KEY = os.environ.get("API_KEY")
        movie_db = MovieDB(API_KEY)
        search_results = movie_db.search_and_return_movie_details(search_query)

        return render_template(
            "search.jinja",
            title="Movies Watchlist - Search Results",
            search_query=search_query,
            search_results=search_results,
        )

    return render_template("search.jinja", title="Movies Watchlist - Database Search")


# Select and add movies route allowing users to select and add movies from search results to their watchlist
@pages.route("/select_add_movie", methods=["POST"])
@login_required
def select_movie():
    selected_movie_ids = request.form.getlist("selected_movie")

    # Add the selected movies to the user's watchlist
    user_id = session["user_id"]

    for movie_id in selected_movie_ids:
        # Fetch details of the selected movie using the MovieDB class
        API_KEY = os.environ.get("API_KEY")
        movie_db = MovieDB(API_KEY)
        movie_details_list = movie_db.search_and_return_movie_details_by_id(movie_id)

        # Iterate over the list of movie details
        for movie_details in movie_details_list:
            # Create a new movie and add it to the database
            new_movie = Movie(
                _id=uuid.uuid4().hex,
                title=movie_details.get("name", ""),
                director=movie_details.get("director", ""),
                year=movie_details.get("year", ""),
                tag1=movie_details.get("tag1", ""),
                tag2=movie_details.get("tag2", ""),
                video_link=movie_details.get("YouTube_Link", ""),
            )

            current_app.db.movies.insert_one(asdict(new_movie))
            current_app.db.user.update_one(
                {"_id": user_id}, {"$push": {"movies": new_movie._id}}
            )

    flash("Selected movies added to your watchlist", "success")
    return redirect(url_for(".index"))

movie_library/templates/macros/fields.jinja
{%macro render_text_field(field)%}
<div class="form__group">
    {{field.label(class="form__label")}}
    {{field(class="form__field")}}

    {% for error in field.errors %}
    <span class="form__error"> {{error}} </span>

    {% endfor %}
</div>


{%endmacro%}


{% macro render_area_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}
    {{ field(rows=4, class_="form__field", style="resize: none") }}

    {%- for error in field.errors %}
    <span class="form__error">{{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}

movie_library/templates/macros/footer.jinja
{% macro footer() %}
<footer class="footer">
    <small>Sercan Dikici &copy;2023. Movies Watchlist</small>
    <small>IU Internationale Hochschule | Task:Project Software Engineering DLMCSPSE01</small>

</footer>
{% endmacro %}

movie_library/templates/macros/nav.jinja
{% macro header(email, theme) %}
<header class="header">
    <div class="nav-container">
        <a href="{{ url_for('pages.index') }}" class="header__logo">
            <img class="logo__icon" src="{{ url_for('static', filename='img/movie.svg') }}" alt="Movie Icon">
            <span class="logo__name">Watchlist</span>
        </a>
        <nav class="nav">

            {% if not email %}
            <a href="{{ url_for('pages.login') }}"
                class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.login') }}">
                <span class="nav__item">Log in</span>
            </a>
            <a href="{{ url_for('pages.register') }}"
                class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.register') }}">
                <span class="nav__item">Register</span>
            </a>

            {% else %}

            <a href="{{ url_for('pages.index') }}"
                class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.index') }}">
                <span class="nav__item">Movies</span>
            </a>
            <a href="{{ url_for('pages.logout') }}" class="nav__link">
                <span class="nav__item">Log out</span>
            </a>

            {% endif %}
        </nav>
    </div>
</header>
{% endmacro %}

movie_library/templates/macros/svgs.jinja
{% macro star(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
        d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
</svg>
{% endmacro %}

{% macro pencil(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
        d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
</svg>
{% endmacro %}

{% macro trash(class_) %}

<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash"
    viewBox="0 0 16 16">
    <path
        d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
    <path fill-rule="evenodd"
        d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
</svg>

{% endmacro %}



{% macro moon(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
        d="M20.354 15.354A9 9 0 018.646 3.646 9.003 9.003 0 0012 21a9.003 9.003 0 008.354-5.646z" />
</svg>
{% endmacro %}

{% macro sun(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" fill="none" viewBox="0 0 24 24" stroke="currentColor">
    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
        d="M12 3v1m0 16v1m9-9h-1M4 12H3m15.364 6.364l-.707-.707M6.343 6.343l-.707-.707m12.728 0l-.707.707M6.343 17.657l-.707.707M16 12a4 4 0 11-8 0 4 4 0 018 0z" />
</svg>
{% endmacro %}


{% macro search(class_) %}
<svg xmlns="http://www.w3.org/2000/svg" class="{{ class_ }}" x="0px" y="0px" width="100" height="100"
    viewBox="0 0 50 50">
    <path
        d="M 21 3 C 11.621094 3 4 10.621094 4 20 C 4 29.378906 11.621094 37 21 37 C 24.710938 37 28.140625 35.804688 30.9375 33.78125 L 44.09375 46.90625 L 46.90625 44.09375 L 33.90625 31.0625 C 36.460938 28.085938 38 24.222656 38 20 C 38 10.621094 30.378906 3 21 3 Z M 21 5 C 29.296875 5 36 11.703125 36 20 C 36 28.296875 29.296875 35 21 35 C 12.703125 35 6 28.296875 6 20 C 6 11.703125 12.703125 5 21 5 Z">
    </path>
</svg>
{% endmacro %}