movie_library/routes.py
from flask import (
    Blueprint,
    render_template,
    url_for,
    session,
    redirect,
    request,
    current_app,
    flash,
)
import functools
from movie_library.forms import MovieForm, Extension, RegisterForm, LoginForm
from dataclasses import asdict
from movie_library.database import MovieDB
import uuid
from movie_library.movies import Movie, User
from passlib.hash import pbkdf2_sha256
import os

# Creating a Flask Blueprint for organized route and view management
pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


# Decorator function to ensure authentication for routes requiring logged-in users
def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))
        return route(*args, **kwargs)

    return route_wrapper


# Home page route displaying the user's watchlist for authenticated users
@pages.route("/")
@login_required
def index():
    # Retrieving user and movie data from the database
    user_data = current_app.db.user.find_one({"email": session["email"]})
    user = User(**user_data)

    movie_data = current_app.db.movies.find({"_id": {"$in": user.movies}})
    mymovies = [Movie(**movie) for movie in movie_data]
    return render_template(
        "index.jinja", title="Movies Watchlist", movies_data=mymovies
    )


# User registration route allowing users to register with a unique email and securely hashed password
@pages.route("/register", methods=["GET", "POST"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))
    form = RegisterForm()

    if form.validate_on_submit():
        # Creating a new user and inserting into the database
        user = User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data),
        )

        current_app.db.user.insert_one(asdict(user))
        flash("User registered succesfully", "Success")

        return redirect(url_for(".login"))

    return render_template(
        "register.jinja", title="Movies Watchlist - Register", form=form
    )


# User login route enabling users to log in securely
@pages.route("/login", methods=["GET", "POST"])
def login():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_data = current_app.db.user.find_one({"email": form.email.data})
        if not user_data:
            flash("Login credentials are not correct", category="danger")
            return redirect(url_for(".login"))
        user = User(**user_data)

        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            # Setting user session upon successful login
            session["user_id"] = user._id
            session["email"] = user.email

            return redirect(url_for(".index"))

        flash("Login credentials are not correct", category="danger")

    return render_template("login.jinja", title="Movie Watchlist - Login", form=form)


# User logout route logging out the currently authenticated user
@pages.route("/logout")
def logout():
    session.clear()
    return redirect(url_for(".login"))


# Add movie route allowing authenticated users to add new movies to their watchlist
@pages.route("/add", methods=["GET", "POST"])
@login_required
def add_movie():
    form = MovieForm()

    if form.validate_on_submit():
        # Creating a new movie and updating the user's watchlist in the database
        movie = Movie(
            _id=uuid.uuid4().hex,
            title=form.title.data,
            director=form.director.data,
            year=form.year.data,
        )
        current_app.db.movies.insert_one(asdict(movie))
        current_app.db.user.update_one(
            {"_id": session["user_id"]}, {"$push": {"movies": movie._id}}
        )

        return redirect(url_for(".index"))

    return render_template(
        "new_movie.jinja", title="Movies Watchlist - Add Movie", form=form
    )


# Edit movie route allowing users to edit details of a specific movie
@pages.route("/edit/movie/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_movie(_id: str):
    movie_data = current_app.db.movies.find_one({"_id": _id})
    movie = Movie(**movie_data)
    form = Extension(obj=movie)

    if form.validate_on_submit():
        # Updating movie details in the database upon form validation
        print(f"Form validated. Values: {form.data}")

        movie.title = form.title.data
        movie.director = form.director.data
        movie.year = form.year.data
        movie.tag1 = form.tag1.data
        movie.tag2 = form.tag2.data
        movie.video_link = form.video_link.data

        current_app.db.movies.update_one({"_id": movie._id}, {"$set": asdict(movie)})
        return redirect(url_for(".movie", _id=_id))
    return render_template("movie_form.jinja", movie=movie, form=form)


# Delete movie route enabling users to delete a specific movie
@pages.route("/delete/movie/<string:_id>", methods=["GET", "POST"])
@login_required
def delete_movie(_id: str):
    current_app.db.user.update_one(
        {"_id": session["user_id"]}, {"$pull": {"movies": _id}}
    )
    return redirect(url_for(".index"))


# View movie details route displaying detailed information about a specific movie
@pages.get("/movie/<string:_id>")
def movie(_id: str):
    movie_data = current_app.db.movies.find_one({"_id": _id})
    movie = Movie(**movie_data)

    return render_template("movie_details.jinja", movie=movie)


# Rate movie route allowing users to rate a specific movie
@pages.get("/movie/<string:_id>/rate")
@login_required
def rate_movie(_id):
    rating = int(request.args.get("rating"))
    current_app.db.movies.update_one({"_id": _id}, {"$set": {"rating": rating}})
    return redirect(url_for(".movie", _id=_id))


# Mark movie as watched route allowing users to mark a movie as watched or not watched
@pages.get("/movie/<string:_id>/watch")
@login_required
def watch_today(_id):
    movie_data = current_app.db.movies.find_one({"_id": _id})

    if movie_data:
        current_state = movie_data.get("last_watched", None)
        new_state = "Not Watched" if current_state == "Watched" else "Watched"

        current_app.db.movies.update_one(
            {"_id": _id}, {"$set": {"last_watched": new_state}}
        )

        flash(f"Movie marked as {new_state}", "Success")

    return redirect(url_for(".movie", _id=_id))


# Search movies route providing a search interface for users to find movies in the database
@pages.route("/search", methods=["GET", "POST"])
@login_required
def search_movies():
    if request.method == "GET":
        return render_template(
            "search.jinja", title="Movies Watchlist - Database Search"
        )

    if request.method == "POST":
        search_query = request.form.get("search_query", "")

        # Use the MovieDB class to search for movies
        API_KEY = os.environ.get("API_KEY")
        movie_db = MovieDB(API_KEY)
        search_results = movie_db.search_and_return_movie_details(search_query)

        return render_template(
            "search.jinja",
            title="Movies Watchlist - Search Results",
            search_query=search_query,
            search_results=search_results,
        )

    return render_template("search.jinja", title="Movies Watchlist - Database Search")


# Select and add movies route allowing users to select and add movies from search results to their watchlist
@pages.route("/select_add_movie", methods=["POST"])
@login_required
def select_movie():
    selected_movie_ids = request.form.getlist("selected_movie")

    # Add the selected movies to the user's watchlist
    user_id = session["user_id"]

    for movie_id in selected_movie_ids:
        # Fetch details of the selected movie using the MovieDB class
        API_KEY = os.environ.get("API_KEY")
        movie_db = MovieDB(API_KEY)
        movie_details_list = movie_db.search_and_return_movie_details_by_id(movie_id)

        # Iterate over the list of movie details
        for movie_details in movie_details_list:
            # Create a new movie and add it to the database
            new_movie = Movie(
                _id=uuid.uuid4().hex,
                title=movie_details.get("name", ""),
                director=movie_details.get("director", ""),
                year=movie_details.get("year", ""),
                tag1=movie_details.get("tag1", ""),
                tag2=movie_details.get("tag2", ""),
                video_link=movie_details.get("YouTube_Link", ""),
            )

            current_app.db.movies.insert_one(asdict(new_movie))
            current_app.db.user.update_one(
                {"_id": user_id}, {"$push": {"movies": new_movie._id}}
            )

    flash("Selected movies added to your watchlist", "success")
    return redirect(url_for(".index"))

movie_library/templates/index.jinja
{% extends "layouts.jinja" %}

{% block head_content %}
<link rel="stylesheet" href="{{url_for('static', filename='css/movies.css')}}">
{% endblock %}

{% block main_content %}

{% if movies_data %}
<table class="table">
    <colgroup>
        <col style="width: 60%">
        <col style="width: 25%">
        <col style="width: 15%">
    </colgroup>
    <thead>
        <tr class="table__header">
            <th class="table__cell table__cell--header">Title</th>
            <th class="table__cell table__cell--header">Release Date</th>
            <th class="table__cell table__cell--header"></th>
        </tr>
    </thead>

    <body>

        {%for movie in movies_data%}
        <tr>
            <td class="table__cell">
                <p class="table__movietitle">{{ movie.title }}</p>
                {% if movie.director %}
                <p class="table__moviedirector">By: {{ movie.director }}</p>
                {% endif %}
                {% if movie.tag1 %}
                <p class="table__moviedirector">Genre: {{ movie.tag1 }} {{ movie.tag2 }}</p>
                {% endif %}
            </td>
            <td class="table__cell">{{ movie.year }}</td>
            <td class="table__cell"><a href="{{url_for('pages.movie', _id=movie._id)}}" class="table__link">View</a>
            </td>
        </tr>
        {%endfor%}

    </body>
</table>

{% else %}
<p class="table__empty">No Movies Added Yet. <a class="link" href="{{url_for('pages.add_movie')}}">Add One!</a>
</p>

{% endif %}

<a class="button button--add" href="{{url_for('pages.add_movie')}}"><span>+</span></a>


{% endblock %}

movie_library/templates/layouts.jinja
{% from "macros/nav.jinja" import header %}
{% from "macros/footer.jinja" import footer %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title | default('Movie Watchlist')}}</title>
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='img/movie.ico') }}">
    <link href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />

    {% block head_content %}

    {% endblock head_content %}

</head>

<body>
    {{header(session.get("email"),session.get("theme"))}}

    <main class="main">
        {% block main_content %}

        {% endblock main_content %}</main>

    {{footer()}}

</body>

</html>

movie_library/templates/login.jinja
{% from "macros/fields.jinja" import render_text_field %}

{% extends "layouts.jinja" %}

{%- block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

<form name="login" method="post" novalidate class="form">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {%- for category, message in messages %}
    <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
    {% endfor %}
    {% endwith %}

    <div class="form__container">
        {{ form.hidden_tag() }}

        {{ render_text_field(form.email) }}
        {{ render_text_field(form.password) }}

        <span class="form__small">
            Don't have an account? <a href="{{url_for('pages.register')}}" class="form__link">Register here</a>.
        </span>

        <div>
            {{ form.submit(class_="button button--form") }}
        </div>
    </div>
</form>

{% endblock %}

movie_library/templates/movie_details.jinja
{% from "macros/svgs.jinja" import star, pencil,trash %}

{% extends "layouts.jinja" %}

{%- block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/movie_details.css') }}" />
{% endblock %}

{% block main_content %}
<div class="container">
    <header class="movie__header">
        <div class="header__row">
            <div class="movie__name">
                <h1>{{ movie.title }}</h1>
                <div class="movie__rating">
                    {% for i in range(5) %}
                    <a class="rating__link" href="{{url_for('pages.rate_movie', _id=movie._id, rating=i+1)}} "> {{
                        star("star "+("star--filled" if movie.rating > i else "")) }}

                    </a>
                    {% endfor %}
                </div>
            </div>
            <div class="movie__watched">
                {% if movie.last_watched == "Watched"%}
                <p>
                    <a href="{{ url_for('pages.watch_today', _id=movie._id) }}" class="watched__link">Watched</a>
                </p>

                {% else %}
                <p><a href="{{url_for('pages.watch_today', _id=movie._id)}}" class="not_watched__link">Not watched
                        yet</a>
                </p>
                {% endif %}

                <a class="movie__edit" href="{{url_for('pages.edit_movie', _id=movie._id)}}">Edit {{ pencil("pencil")
                    }}</a>

                <a method="post" class="movie__delete" href="{{url_for('pages.delete_movie', _id=movie._id)}}">Delete {{
                    trash("trash")
                    }}</a>

            </div>
        </div>
        <div class="header__row">
            <ul class="movie__tags">
                {% if movie.tag1 %}
                <li class="movie__tag">{{ movie.tag1 }}</li>
                {% endif %}
                {% if movie.tag2 %}
                <li class="movie__tag">{{ movie.tag2 }}</li>
                {% endif %}
            </ul>
        </div>



    </header>
    {% if movie.video_link %}
    <iframe class="movie__video" src="{{ movie.video_link }}" title="YouTube video player" frameborder="0"
        allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen>
    </iframe>
    {% endif %}

</div>
{% endblock %}

movie_library/templates/movie_form.jinja
{% from "macros/fields.jinja" import render_text_field, render_area_field %}

{% extends "layouts.jinja" %}

{%- block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

<form name="add_movie" method="post" novalidate class="form">
    <div class="form__container">
        {{ form.hidden_tag() }}
        {{ render_text_field(form.title) }}
        {{ render_text_field(form.director) }}
        {{ render_text_field(form.year) }}
        {{ render_text_field(form.tag1) }}
        {{ render_text_field(form.tag2) }}
        {{ render_text_field(form.video_link) }}

        <div>
            {{ form.submit(class_="button button--form") }}
        </div>

    </div>
</form>

{% endblock %}

movie_library/templates/new_movie.jinja
{% from "macros/fields.jinja" import render_text_field%}
{% from "macros/svgs.jinja" import search %}

{% extends "layouts.jinja" %}

{% block head_content %}
<link rel="stylesheet" href="{{url_for('static', filename='css/forms.css')}}">
{% endblock head_content %}

{% block main_content %}



<form name="add_movie" method="post" , novalidate class="form">
    <div class="form__container">
        <p>
            <a class="form__container--search" href="{{url_for('pages.search_movies')}}">Search{{
                search("search")}}</a>
        </p>
        {{form.hidden_tag()}}
        {{render_text_field(form.title)}}
        {{render_text_field(form.director)}}
        {{render_text_field(form.year)}}

        <div>
            {{form.submit(class_="button button--form")}}
        </div>
    </div>

</form>

{% endblock main_content %}

movie_library/templates/register.jinja
{% from "macros/fields.jinja" import render_text_field %}

{% extends "layouts.jinja" %}

{%- block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

<form name="register" method="post" novalidate class="form">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {%- for category, message in messages %}
    <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
    {% endfor %}
    {% endwith %}

    <div class="form__container">
        {{ form.hidden_tag() }}

        {{ render_text_field(form.email) }}
        {{ render_text_field(form.password) }}
        {{ render_text_field(form.confirm_password) }}

        <span class="form__small">
            Already have an account? <a href="{{url_for('pages.login')}}" class="form__link">Log in here</a>.
        </span>

        <div>
            {{ form.submit(class_="button button--form") }}
        </div>
    </div>
</form>

{% endblock %}

movie_library/templates/search.jinja
{% from "macros/fields.jinja" import render_text_field, render_area_field %}

{% extends "layouts.jinja" %}

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-success">
    {{ messages[0] }}
</div>
{% endif %}
{% endwith %}

{%- block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}
<div class="db_container">
    <h1 class="dbtitle">{{ title }}</h1>

    <form class="dbsearch" method="post" action="{{ url_for('pages.search_movies') }}">
        <input class="dbform_field" type="text" id="search_query" name="search_query"
            placeholder="Please enter a movie name">
        <button class="dbsearch_button" type="submit">Search</button>
    </form>

    {% if search_results %}
    <form class="dbsearch" name="add_movie" method="post" novalidate class="form"
        action="{{ url_for('pages.select_movie') }}">

        <ul>
            {% for movie in search_results %}
            <li>
                <div class="movie_container">
                    <input class="select_movie" type="checkbox" id="movie_{{ movie['ID'] }}" name="selected_movie"
                        value="{{ movie['ID'] }}">
                    <div class="movie_selection">
                        <label class="movie_label" for="movie_{{ movie['ID'] }}">
                            <div class="movie_info">
                                <h3 class="movie_name">{{ movie['name'] }}</h3>
                                <div class="movie_details">
                                    <p class="year"><strong>Year:</strong> {{ movie['year'] }}</p>
                                    <p class="director"><strong>Director:</strong> {{ movie['director'] }}</p>
                                    <p class="tags"><strong>Tags:</strong> {{ movie['tag1'] }} {{ movie['tag2'] }}</p>
                                </div>
                            </div>
                        </label>
                    </div>

                    {% if movie['image_Link'] and not movie['image_Link'].endswith('N/A') %}
                    <img class="movie_img" src="{{ movie['image_Link'] }}" alt="{{ movie['name'] }} Image">
                    {% else %}
                    <p class="notaval">No img available</p>
                    {% endif %}
                </div>
            </li>

            {% endfor %}
        </ul>

        <button class="dbselect_button" type="submit">Add Movie</button>
    </form>

    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="alert alert-success">
        {{ messages[0] }}
    </div>
    {% endif %}
    {% endwith %}
    {% elif search_query %}
    <p class="dbsearch_noresult">No results found for '{{ search_query }}'.</p>
    {% endif %}
</div>

{% endblock main_content %}

movie_library/templates/search2.jinja
{% extends "layouts.jinja" %}

{%- block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}
<div class="db_container">
    <h1 class="dbtitle">{{ title }}</h1>

    <form class="dbsearch" method="post" action="{{ url_for('pages.search_movies') }}">
        <label class="dbsearch__label" for="search_query">Search for movies:</label>
        <input class="dbform_field" type="text" id="search_query" name="search_query" required>
        <button class="dbsearch_button" type="submit">Search</button>

    </form>
</div>

{% if search_results %}
<h2>Search Results for '{{ search_query }}':</h2>
<form method="post" action="{{ url_for('pages.select_movie') }}">
    <ul>
        {% for movie in search_results %}
        <li>
            <input type="radio" id="movie_{{ movie['ID'] }}" name="selected_movie" value="{{ movie['ID'] }}" required>
            <label for="movie_{{ movie['ID'] }}">
                <h3>{{ movie['name'] }}</h3>
                <p><strong>Year:</strong> {{ movie['year'] }}</p>
                <p><strong>Director:</strong> {{ movie['director'] }}</p>
                <p><strong>Tags:</strong> {{ movie['tag'] }}</p>
                {% if movie['image_Link'] and not movie['image_Link'].endswith('N/A') %}
                <img src="{{ movie['image_Link'] }}" alt="{{ movie['name'] }} Image">
                {% else %}
                <p>No image available</p>
                {% endif %}

            </label>
        </li>
        {% endfor %}
    </ul>
    <button type="submit">Select Movie</button>
</form>

{% endif %}
{% if search_query %}
<p class="dbsearch_noresult">No results found for '{{ search_query }}'.</p>
{% endif %}

{% endblock main_content%}

movie_library/templates/search3.jinja
{% from "macros/fields.jinja" import render_text_field, render_area_field %}

{% extends "layouts.jinja" %}

{% with messages = get_flashed_messages() %}
{% if messages %}
<div class="alert alert-success">
    {{ messages[0] }}
</div>
{% endif %}
{% endwith %}

{%- block head_content %}
<link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}
<div class="db_container">
    <h1 class="dbtitle">{{ title }}</h1>

    <form class="dbsearch" method="post" action="{{ url_for('pages.search_movies') }}">
        <input class="dbform_field" type="text" id="search_query" name="search_query">
        <button class="dbsearch_button" type="submit">Search</button>

        {% if search_results %}
        <form name="add_movie" method="post" novalidate class="form" action="{{ url_for('pages.select_movie') }}">
            <ul>
                {% for movie in search_results %}
                <li>
                    <div class="movie_container">
                        <input class="select_movie" type="checkbox" id="movie_{{ movie['ID'] }}" name="selected_movie"
                            value="{{ movie['name'] }}">
                        <div class="movie_selection">
                            <label class="movie_label" for="movie_{{ movie['ID'] }}">
                                <div class="movie_info">
                                    <h3 class="movie_name">{{ movie['name'] }}</h3>
                                    <div class="movie_details">
                                        <p class="year"><strong>Year:</strong> {{ movie['year'] }}</p>
                                        <p class="director"><strong>Director:</strong> {{ movie['director'] }}</p>
                                        <p class="tags"><strong>Tags:</strong> {{ movie['tag'] }}</p>
                                    </div>
                                </div>
                            </label>
                        </div>

                        {% if movie['image_Link'] and not movie['image_Link'].endswith('N/A') %}
                        <img class="movie_img" src="{{ movie['image_Link'] }}" alt="{{ movie['name'] }} Image">
                        {% else %}
                        <p class="notaval">No img available</p>
                        {% endif %}
                    </div>
                </li>

                {% endfor %}
            </ul>

            <button class="dbselect_button" type="submit">Add Movie</button>
        </form>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-success">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
        {% elif search_query %}
        <p class="dbsearch_noresult">No results found for '{{ search_query }}'.</p>
        {% endif %}
    </form>
</div>

{% endblock main_content %}